basePath: /api/v1
definitions:
  models.Pokemon:
    properties:
      abilities:
        description: Abilities
        example:
        - '["static"]'
        items:
          type: string
        type: array
      height:
        description: Height
        example: 4
        type: integer
      id:
        description: ID of the Pokemon
        example: 25
        type: integer
      name:
        description: Name
        example: pikachu
        type: string
      sprites:
        allOf:
        - $ref: '#/definitions/models.Sprites'
        description: Sprites
      types:
        description: Types
        example:
        - '["electric"]'
        items:
          type: string
        type: array
      weight:
        description: Weight
        example: 60
        type: integer
    type: object
  models.Sprites:
    properties:
      back_default:
        description: Back sprite
        example: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png
        type: string
      front_default:
        description: Front sprite
        example: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A simple REST API for Pokemon data
  title: Pokemon API
  version: "1.0"
paths:
  /pokemon/random:
    get:
      description: Fetches a random Pokemon
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Pokemon'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a random Pokemon
      tags:
      - pokemon
swagger: "2.0"
